### ISSUE TITLE
disc.py doesn't read expression matrix correctly, it mixes columns up!

### ISSUE THREAD

**Issue by Jintram** [woojunshim/TRIAGE#3]
Dear Woo Jun / others,

Nice paper! I do think the code has a serious issue:

I supplied disc.py with an input matrix of the following format:

```
Cell1 Cell2
Gene1 0 0.3
Gene2 10 8
```

Correct me if I'm wrong, but I think this is standard practice (it's simply the output of R's write.table function).

This was not read correctly by the import function in disc.py, all columns were shifted, such that the expression values of the 1st column with data where coupled to the name "cell 2", and so on.
I think this goes wrong because in the script the column name i is matched with column i, but the column names line is one element shorter than the other lines, so it ends up matching incorrect lines.
Below is a suggested fix (original now corrected code line commented out).

```
def read_input(filename): 
    """ read an input file """
    temp = []
    results = {}        
    file_ = open(filename, 'r')
    for line in file_:
        line = line.strip().split()            
        temp.append(line)
    for t1 in temp[1:]:
        results[t1[0]] = {}
        for idx in range(1, len(temp[0])):
            # t2 = temp[0][idx]            
            t2 = temp[0][idx-1]
            results[t1[0]][t2] = float(t1[idx])
    return results
```

Cheers, Martijn

**Comment by woojunshim** [comment]
Thanks, Martijn. 

I've addressed this issue in the previous posting. 

Best Regards,
Woo Jun (Chris)

**Comment by Jintram** [comment]
Many thanks, also for the quick reply! 

I now realize that what R outputs might not necessarily be the "golden standard" of tsv files.

Indeed, in R, `write.table(file = 'myfile.tsv', x = my_matrix, quote = F, sep='\t')` produces a first row with n-1 elements.
But standard python is probably something like `df.to_csv(path_or_buf='myfile.tsv',  index=True, sep='\t')` which indeed produces a first row with n elements. 
Very confusing :)

So great that you made both options possible!

**Comment by woojunshim** [comment]
No worries and Thanks for pointing it out. 

Best,
Woo Jun (Chris)
